Traceback (most recent call last):
  File "/Users/taka/projects/fxbot/trade_bot.py", line 25, in <module>
    model  = tf.keras.models.load_model(MODEL_DIR, compile=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taka/projects/fxbot/fxbot-env/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taka/projects/fxbot/fxbot-env/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/taka/projects/fxbot/fxbot-env/lib/python3.11/site-packages/keras/src/saving/legacy/save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at /Users/taka/projects/fxbot/lstm_fx_saved
zsh:1: command not found: python
zsh:1: command not found: python
zsh:1: command not found: python
zsh:1: command not found: python
